### ISSUE TITLE
[BUG] Cannot Decode JSON Unexpected Application Error on Paring

### ISSUE THREAD

**Issue by comanche** [vultisig/vultisig-windows#460]
**Describe the bug**

Getting an **Unexpected Application Error!** when pairing Vultisig 1.0.3 to existing vault.

This is the error:

```
Unexpected Application Error!
cannot decode vultisig.keygen.v1.ReshareMessage from JSON: Unterminated string in JSON at position 405 (line 1 column 406)
Error: cannot decode vultisig.keygen.v1.ReshareMessage from JSON: Unterminated string in JSON at position 405 (line 1 column 406)
    at zs.fromJsonString (http://wails.localhost/assets/index-d883f60f.js:505:2366)
    at fromJsonString (http://wails.localhost/assets/index-d883f60f.js:1173:15842)
    at http://wails.localhost/assets/index-d883f60f.js:1173:26250
    at Object.useMemo (http://wails.localhost/assets/index-d883f60f.js:43:25846)
    at react_production_min.useMemo (http://wails.localhost/assets/index-d883f60f.js:9:7273)
    at useCurrentJoinKeygenMsg (http://wails.localhost/assets/index-d883f60f.js:1173:26185)
    at JoinKeygenPage (http://wails.localhost/assets/index-d883f60f.js:1208:7027)
    at Nh (http://wails.localhost/assets/index-d883f60f.js:43:18892)
    at Vk (http://wails.localhost/assets/index-d883f60f.js:45:48504)
    at Uk (http://wails.localhost/assets/index-d883f60f.js:45:43758)
```

**To Reproduce**
1. On iPhone, goto top left menu icon and navigate to **Vault Settings > Reshare**
2. Click on **Start Reshare**
3. On the top right, click on the export button
4. Save QR code somewhere you can access from your Windows computer
5. Start brand new Vultisig 1.0.3 (brand new installation) on your computer
6. Select on **Secure** at top
7. Select **Pair** at the bottom
8. Upload the QR code from step 4 above
9. Click on **Continue**
10. Error shows up.

**Expected behavior**
Vultisig on Windows should pair with Vultisig on iPhone.

**Screenshots**

![Screenshot](https://github.com/user-attachments/assets/9b706174-c02a-4778-8092-7ac6644fb47b)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 64-bit
 - Version: 24H2 build 26100.2161

**Additional context**

**Comment by johnnyluo** [comment]
Thanks @comanche for reporting this
