### ISSUE TITLE
[BUG] Fix compile issue when there is call into "initWasm" from wallet-core

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-windows#53]
Currently , if we trying to call `initWasm` function from `wallet-core` anywhere on our webpage, and then when we trying to build it , it will spit out an error
```
[commonjs--resolver] Could not load /Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/node-stdlib-browser/cjs/mock/empty.js/promises: ENOTDIR: not a directory, open '/Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/node-stdlib-browser/cjs/mock/empty.js/promises'
file: /Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/@trustwallet/wallet-core/dist/index.js
error during build:
Error: Could not load /Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/node-stdlib-browser/cjs/mock/empty.js/promises: ENOTDIR: not a directory, open '/Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/node-stdlib-browser/cjs/mock/empty.js/promises'
    at async open (node:internal/fs/promises:637:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
    at async file:///Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/rollup/dist/es/shared/node-entry.js:24611:75
    at async Queue.work (file:///Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25654:32)
npm verb lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
npm verb lifecycle frontend@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/johnnyluo/project/wallets/vultisig-windows/frontend/node_modules/.bin:/Users/johnnyluo/bin:/usr/local/bin:/Users/johnnyluo/go/bin:/usr/local/go/bin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/make/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/gawk/libexec/gnubin:/Applications/GoLand.app/Contents/MacOS:/Users/johnnyluo/Library/Android/sdk/tools:/Users/johnnyluo/Library/Android/sdk/tools/bin:/Users/johnnyluo/Library/Android/sdk/platform-tools:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/johnnyluo/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.darwin-amd64/bin:/Users/johnnyluo/go/bin:/Users/johnnyluo/bin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/make/libexec/gnubin:/usr/local/opt/gawk/libexec/gnubin:/Applications/GoLand.app/Contents/MacOS:/Users/johnnyluo/Library/Android/sdk/tools:/Users/johnnyluo/Library/Android/sdk/tools/bin:/Users/johnnyluo/Library/Android/sdk/platform-tools:/Users/johnnyluo/.cargo/bin
npm verb lifecycle frontend@0.1.0~build: CWD: /Users/johnnyluo/project/wallets/vultisig-windows/frontend
npm info lifecycle frontend@0.1.0~build: Failed to exec build script
npm verb stack Error: frontend@0.1.0 build: `tsc && vite build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (node:events:519:28)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (node:events:519:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verb pkgid frontend@0.1.0
npm verb cwd /Users/johnnyluo/project/wallets/vultisig-windows/frontend
npm verb Darwin 23.5.0
npm verb argv "/usr/local/Cellar/node/21.7.3/bin/node" "/usr/local/bin/npm" "run" "build" "--verbose"
npm verb node v21.7.3
npm verb npm  v6.14.8
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `tsc && vite build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 4504ms
```

**Comment by johnnyluo** [comment]
it seems there is some conflict between wallet-core and "node-stdlib-browser"

```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import stdLibBrowser from 'vite-plugin-node-stdlib-browser';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), stdLibBrowser()],
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
  },
  publicDir: 'public',
  resolve: {
    alias: {
      crypto: 'crypto-browserify',
      stream: 'stream-browserify',
      buffer: 'buffer',
    },
  },
  optimizeDeps: {
    include: ['crypto-browserify', 'stream-browserify', 'buffer'],
  },
});

```
